//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("reloc ver:1.4.31115.5")]
[assembly: System.Reflection.AssemblyDescription("relocates the current console window.")]
[assembly: System.Reflection.AssemblyCompany("Bricksoft.com")]
[assembly: System.Reflection.AssemblyProduct("reloc")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (C) 2010-2013 Kody Brown. Application and source code released under th" +
    "e MIT License.")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: System.Runtime.InteropServices.Guid("594CA055-3BF8-47EC-B5C1-F8B57390396C")]
[assembly: System.Reflection.AssemblyVersion("1.4.31115.5")]
[assembly: System.Reflection.AssemblyFileVersion("1.4.31115.5")]


